### ISSUE TITLE
Version 0.4.4 (latest) does not ship with types 

### ISSUE THREAD

**Issue by pastelsky** [redis/redis-om-node#241] opened 2024-07-16 06:23 UTC
The latest version does not ship with type definitions — 
https://unpkg.com/browse/redis-om@0.4.4/dist/

however, the older versions seem to have it —

https://unpkg.com/browse/redis-om@0.4.3/dist/

**Comment by guyroyse** [comment] 2024-07-16 14:36
Published on NPM under version 0.4.6. Looks like NPM's behavior around glob-style paths in the files property of package.json changed. Sorry for any inconvenience.

**Comment by pastelsky** [comment] 2024-07-17 11:55
So `0.4.6` has type definitions now (thanks!). However I see that the `client` type (as defined by `redis`) and that expected by `redis-om` do not seem to match.

This means this throws a type error — 

```
import { createClient } from 'redis';
import { Repository } from 'redis-om';

import { createClient } from 'redis';
import { branchSchema } from '../entities/branch.entity';

const client = createClient();
new Repository(branchSchema, client);

```

### Error
```
 error TS2345: Argument of type 'RedisClientType<{ graph: { CONFIG_GET: typeof import("/project/node_modules/@redis/graph/dist/commands/CONFIG_GET"); configGet: typeof import("/project/node_modules/@redis/graph/dist/commands/CONFIG_GET"); ... 15 more ...; slowLog: t...' is not assignable to parameter of type 'Client | RedisConnection'.
  Type 'import("/project/node_modules/@redis/client/dist/lib/client/index").RedisClientType<{ graph: { CONFIG_GET: typeof import("/project/node_modules/@redis/graph/dist/commands/CONFIG_GET"); configGet: typeof import("/project...' is not assignable to type 'import("/project/node_modules/redis-om/node_modules/@redis/client/dist/lib/client/index").RedisClientType<{ graph: { CONFIG_GET: typeof import("/project/node_modules/@redis/graph/dist/commands/CONFIG_GET"); configGet: typeof import("...'.
    Type 'import("/project/node_modules/@redis/client/dist/lib/client/index").RedisClientType<{ graph: { CONFIG_GET: typeof import("/project/node_modules/@redis/graph/dist/commands/CONFIG_GET"); configGet: typeof import("/project...' is not assignable to type 'import("/project/node_modules/redis-om/node_modules/@redis/client/dist/lib/client/index").RedisClientType<{ graph: { CONFIG_GET: typeof import("/project/node_modules/@redis/graph/dist/commands/CONFIG_GET"); configGet: typeof import("...'.
      Property '#private' is missing in type 'import("/project/node_modules/@redis/client/dist/lib/client/index").default<{ graph: { CONFIG_GET: typeof import("/project/node_modules/@redis/graph/dist/commands/CONFIG_GET"); configGet: typeof import("/projectian/uip-...' but required in type 'import("/project/node_modules/redis-om/node_modules/@redis/client/dist/lib/client/index").default<{ graph: { CONFIG_GET: typeof import("/project/node_modules/@redis/graph/dist/commands/CONFIG_GET"); configGet: typeof import("/Users/s...'.

15     this.branchRepository = new Repository(branchSchema, createClient());
                                                            ~~~~~~~~~~~~~~~~~~~

  node_modules/redis-om/node_modules/@redis/client/dist/lib/client/index.d.ts:92:5
    92     #private;
           ~~~~~~~~
    '#private' is declared here.
    ```

**Comment by guyroyse** [comment] 2024-07-17 14:06
I'll dig into it. In my defense, the unit and integration tests did pass. ;)

**Comment by guyroyse** [comment] 2024-07-17 17:23
Okay. I'm not able to reproduce this but I do see a bug in error and your sample code:

```typescript
const repository = new Repository(branchSchema, createClient());
```

You need to pass in a connected client to Repository:

```typescript
const client = createClient()
await client.connect()

const repository = new Repository<BoringEntity>(boringSchema, client)
```

When I do this, it works just fine. However, when I tried doing it without connecting, I don't get the same error message as you. Instead, I get this one:

```
/Users/guyroyse/code/redis/om-node/issue-241/node_modules/redis/node_modules/@redis/client/dist/lib/client/index.js:510
        return Promise.reject(new errors_1.ClientClosedError());
                              ^

ClientClosedError: The client is closed
    at Commander._RedisClient_sendCommand (/Users/guyroyse/code/redis/om-node/issue-241/node_modules/redis/node_modules/@redis/client/dist/lib/client/index.js:510:31)
    at Commander.commandsExecutor (/Users/guyroyse/code/redis/om-node/issue-241/node_modules/redis/node_modules/@redis/client/dist/lib/client/index.js:190:154)
    at Commander.<computed>.<computed> [as set] (/Users/guyroyse/code/redis/om-node/issue-241/node_modules/redis/node_modules/@redis/client/dist/lib/commander.js:58:33)
    at Client.jsonset (/Users/guyroyse/code/redis/om-node/issue-241/node_modules/redis-om/dist/index.js:1786:27)
    at Repository.writeEntityToJson (/Users/guyroyse/code/redis/om-node/issue-241/node_modules/redis-om/dist/index.js:1685:23)
    at Repository.writeEntity (/Users/guyroyse/code/redis/om-node/issue-241/node_modules/redis-om/dist/index.js:1658:91)
    at Repository.save (/Users/guyroyse/code/redis/om-node/issue-241/node_modules/redis-om/dist/index.js:1611:16)
    at async main (file:///Users/guyroyse/code/redis/om-node/issue-241/dist/app.js:12:14)
```

Can you try connecting and seeing of the error goes away? If it doesn't, could you provide a sample repo that reproduces the error?

Thanks!

**Comment by guyroyse** [comment] 2024-07-22 14:00
Any movement on your side @pastelsky? Can I close this issue?

**Closed** 2024-07-29 15:29 UTC
Labels: bug

**Comment by ladderschool** [comment] 2025-06-19 21:26
Years later I seem to have a similar issue with the graph. These are my packages:
```
    "redis": "4.7.0",
    "redis-om": "0.4.7",
    "@redis/client": "1.6.0",
    "@redis/graph": "1.1.1",
    "@redis/json": "1.0.7",
    "@redis/search": "1.2.0",
```
My code:
```
import { createClient } from 'redis'

export const createRedisClient = (db = 0) => {
  const client = createClient({
    url: process.env.REDIS_URL,
  })

  client.on('connect', () => {
    client.select(db)
  })

  return client
}

export const redis = createRedisClient()

// Then I use this to create a redis-om repository:

export const connectionsRepository = new Repository(connectionSchema, **redis**)
```
The redis client shows a typescript error:
```
Argument of type 'RedisClientType<{ graph: { CONFIG_GET: typeof import("<path>/node_modules/@redis/graph/dist/commands/CONFIG_GET"); configGet: typeof import("<path>/node_modules/@redis/graph/dist/commands/CONFIG_GET"); ... 15 more ...; slowLog: typeof import("<path>...' is not assignable to parameter of type 'Client | RedisConnection'.
index.d.ts(92, 5): '#private' is declared here.
```
If I import the createClient from '@redis/client' I get a similar error:
```
Argument of type 'RedisClientType<RedisModules, RedisFunctions, RedisScripts>' is not assignable to parameter of type 'Client | RedisConnection'.
  Type 'RedisClientType<RedisModules, RedisFunctions, RedisScripts>' is not assignable to type 'RedisClientType<{ graph: { CONFIG_GET: typeof ...
```
Here's my tsconfig.json:
```
{
  "compilerOptions": {
    "noEmit": true,
    "allowJs": true,
    "esModuleInterop": true,
    "target": "esnext",
    "module": "esnext",
    "moduleResolution": "bundler",
    "allowSyntheticDefaultImports": true,
    "skipLibCheck": true,
    "forceConsistentCasingInFileNames": true,
   }
}
```

**Comment by ladderschool** [comment] 2025-06-19 21:27
Years later I seem to have a similar issue with the graph. These are my packages:
```
    "redis": "4.7.0",
    "redis-om": "0.4.7",
    "@redis/client": "1.6.0",
    "@redis/graph": "1.1.1",
    "@redis/json": "1.0.7",
    "@redis/search": "1.2.0",
```
My code:
```
import { createClient } from 'redis'

export const createRedisClient = (db = 0) => {
  const client = createClient({
    url: process.env.REDIS_URL,
  })

  client.on('connect', () => {
    client.select(db)
  })

  return client
}

export const redis = createRedisClient()

// Then I use this to create a redis-om repository:
redis.connect()

export const connectionsRepository = new Repository(connectionSchema, redis)
```
The redis client shows a typescript error:
```
Argument of type 'RedisClientType<{ graph: { CONFIG_GET: typeof import("<path>/node_modules/@redis/graph/dist/commands/CONFIG_GET"); configGet: typeof import("<path>/node_modules/@redis/graph/dist/commands/CONFIG_GET"); ... 15 more ...; slowLog: typeof import("<path>...' is not assignable to parameter of type 'Client | RedisConnection'.
index.d.ts(92, 5): '#private' is declared here.
```
If I import the createClient from '@redis/client' I get a similar error:
```
Argument of type 'RedisClientType<RedisModules, RedisFunctions, RedisScripts>' is not assignable to parameter of type 'Client | RedisConnection'.
  Type 'RedisClientType<RedisModules, RedisFunctions, RedisScripts>' is not assignable to type 'RedisClientType<{ graph: { CONFIG_GET: typeof ...
```
Here's my tsconfig.json:
```
{
  "compilerOptions": {
    "noEmit": true,
    "allowJs": true,
    "esModuleInterop": true,
    "target": "esnext",
    "module": "esnext",
    "moduleResolution": "bundler",
    "allowSyntheticDefaultImports": true,
    "skipLibCheck": true,
    "forceConsistentCasingInFileNames": true,
   }
}
```
